apiVersion: v1
kind: ResourceQuota
metadata:
  name: comicrent-quota
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"

spec:
  hard:
    requests.cpu: "2"
    requests.memory: "2Gi"

    limits.cpu: "4"
    limits.memory: "4Gi"

    requests.storage: "10Gi"

    pods: "20"
    persistentvolumeclaims: "5"

    services: "15"
    configmaps: "20"
    secrets: "15"