{{- if .Values.p9Mode }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: comicrent-auth-secret
  namespace: sa-p9
spec:
  encryptedData:
    ENCRYPTION_KEY: AgADJRWUp/BxopVt6FFYtm5E5VLit2AECMKpKZN/9S87e8e8y49zwwGSIMZj0R1qL6DJgVjVbQEgWAT/hQEKd/AURWRZqZ+ipw88tGSKsfAdZD2pqYbL9vIC5EmiZ+hVbIoMObh1uVIpBuZKK6JEIP101YvlU6a5pMitZaCTNAc0faez8pDd6W5GpT959MtsMAeNzk6Mw/LUTlzbaV58SOcDNNFiu8B3dAqw8uUD34R1ELKScwBSKhgWyUzI+/7BXbuCsQTsn0kV6ahaNTxQzjX4/CFAsJVNOIqEwqaF3Y30T7JN0VKFmbokz1l+IFjzgnyNtx2z/M/tgL0Ew4DWdtb9v30C/xP7wLMQvm84r9wL1IN+srKB0VccJCFKTiUplzlr1iDm4um54GEVQHl+fIgEFhnJvtOR4TsqIvoMAR9AOv0y5vgCpZKBlOIta3efCl88VvYaVoDgOfAv4yNYprCKfHzr0Kuhq2ZuWZ5sgGD1YTE0Q2ocPrjN3VGrIw13CIYmE9no/CybvpOmB/nMFdvoxSewbyO6Z/bkmH1tYCZ3P6BocnV4g/IdstscSz6Xuf/FyYc+UmN4xhnimIzsfJ5Cnv0WTpBwYjKGEjEqqgjVHsdhKNN5ZvO/cjc6LCGSsSAIrEyvnUDik2bl69PivGqekO8q60CxvYFOiStr2DnNrOXpodL2nDfEJxXpi3uFnj7cm1gjlLt+FVGkPPhPp+dBuUexokG8JejEqomJd1QB0jw5j71vCSXO8aYWAS0Ggc576IpYKLQ/otYE/31HM1lP
    JWT_SECRET: AgCDii5H+tIcrIfRpjrknaAmSAmso+KqQXEgcFQe3SFEkN+wvs+CgdhjZam4yosq5iOkYK6pJx7FD8ZH4VDvxOGCmy4S7T0QuDLkud6kS3MYwJbBBaB+fv9torEMi958qGaBjFC/K/0fpQNcfZ0l1Tiu0qaWHR2COE19Kzp7wF1XDA7viq7yS3gWClXyTOO2Py7bPI1hd4ajR2Ujmky+yFPvLRwUqkfjmFnXlFeGv4b5YUgG9fFyYW6bgP1Bf59RTzYeio2Iy1ZhuNrPqrV5Tt5PaKx9gAHEwWV19G7k8oyEWDXm69wfWsANFUeA4UA11sVDiwY8hVt2kmBaQ9AH35wy55BgLoyWoVJvZe/LKXdEbIF6fLeywQZ4eTF5cq7sm/KPv5JukdrokRVhtDK6+6VzDhrI87Ck+BwXzftIOml0BcKpAIDsZfd7/YUs4HHKB8aMXNqac3D833F+4sVWpe6W3jrND0YpVG14Sdu4tCdOjY26P1rmLG+xSdzEMCMnC0a5XNc/UknsWkRhmAiAk5S9CtWzC8XtVhFghU7JabjmkL0xTNXQpvuZa5KVsLRacvGMp1SfPk77WuZrSKIUGa0612GN+jB/eL+6b+ec2OX3O7pf0LXM/3nG7LXxBULF3OnfapqElYNMMAnrnfvwK1FqlMyyeIvPauOXSXTeofVy0qJz1dcqs2lXOsEXGHjCe4t7MDvdabaQCEdcNCv3S79fxckn/aMtGvdFC+zVGTZHAPWtINp8OG/wBc47ZVlSM1tcN4t1ZKAp4vvVq6A8/SON
  template:
    metadata:
      creationTimestamp: null
      name: comicrent-auth-secret
      namespace: sa-p9
    type: Opaque
{{- end }}
