{{- if not .Values.p9Mode }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: comicrent-auth-secret
  namespace: sa-p8
spec:
  encryptedData:
    ENCRYPTION_KEY: AgAZOQdHUU2YFWw8Bh3Uxh3UIIMZDdd1XY+Ga/G1Td4MeU276hiooeQU22ZGLGvqvMYvJODbyO438qCRLc73UeadkOygxnfsHSdc1JuNqNNf90KQ4OR0nVfqAW7yJIBovj+yNJecVm4krmpTYPeMDBYq8nJAS/weI953eL/DI80+k5Rqi7Hw88/d8haXxsb47fHGQIuEE0kpBYpef7N1TRgfQ6ppi/5unvsT9+gzCciInP+u8CgiuArMhrZ3K5afg2RHH8KojgYeSICozCVqZ0GBLEpVLsvwQXHCfAh0yfthMub6gMGg9KXgoGXx003TRh+IxMdvRA9/xY14r+Pnui/00KVOZ6vtfLzzNUWDHYMKU1NKc63Tv6eM4B/snO4m2jlFWq7XU5AcQzSR0wkzzToYTrY3BFUWCN9ahUzd8++tJVXnv+iaV43AhIYwcMh/74nhBNRmk3g5O8OIn6bFhoTrTZT8ogldd7gIB+ZQ4s6cNrJ+Co3O9rcEIpaGAcqUga2MqlgqDUnwWIj2VbzqHix/lfFoYQFOaTDtCRrY7EKpgdoKsosjJoyKbTaXMleM3rTVOBxcQ6qeQ+RUSvLVVES1gneOsoaiLevvKZDPt3v1oT+Sar+NNWnC2y4ju34fhwgdz3WAXNyHpTQ3joxGrgq3nAh0LR1WtAipVnIImsNea/6x/jeyGCynacy4qGRTh5rtVxBPD0ovlzMFOnXIyjyluTQuTt7K6TdvgazPfJOoxuTpu6AsBqNxieaNQ29nc892NueANuDN8vup5S8Lt0qv
    JWT_SECRET: AgCZP4yKxHX1uOrHqDu86bM2jf+k4jgDhgpL9OmLNbvdZhEDHKnIU8c0J1xqVde4zlP9nguyDWE2+x4E72RfyAXXGATzkbcOIz4xvVfstYlnr94JIZ1R90NJ5g1JUvHIiY5u4FnkJkJnZPg9V8xJlDaKvgpveLKAAprcqsjcRhz51XmiJXBvohW8heltjgM3BMJ8skh16ksDltPcCm/VVzeBQPgGoBalm3u4O0s9Jcrjrp7XL5uCcSY6mUfYz4drl1MUb709j85MlqG9aAbHjgUe18oWceHDaGl0WLegIaHkiazhMr3A5hXqOJtoZgU1W/wGv9xZh9IHLuzekQ0Znzgk7vAVIngyCcqQGxm2r2DuWH5Fvnmg7fqVi/37jevbIZoUY2iUX/AkgKtszQLZeJVhue0oVOzkDCM8bw+FWJJuWywmIlSEnHIgx5ktv6MsgxhCITD/q8qYrE1NVIavgtHTv2Jn4BVHZvXtcxzZD0Tl2DKznfWbiQN9nmE1KKqBEgc8AwPPjz/ZdCxrN0DqIWYiIuUqCGSV9OrMUa90CbCASruneQD/07R838i/Gg+6fuL2W5zJZ0sm17WKhtrnskb8zjWaiCsr4WQLZ/9TLIMWrjDbQNp0RQwU4GiCSZ8zs2qqwsv/QaWnL0td0RXN2GYG/53WLKN71IvlZ+jsC+UrrGu/KtEQbEcgDc/UuobHG+ZTeg90dW5mw3vdJ9I5v8uI1AI7MLJXoO2S8nB+diUp8ndi4xrL7Mku5JSZJ9zd3SByp0u5H7Cp/Tyan7oFjPU9
  template:
    metadata:
      creationTimestamp: null
      name: comicrent-auth-secret
      namespace: sa-p8
    type: Opaque

{{- end }}

