---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: comicrent-rabbitmq-secret
  namespace: sa-p8
spec:
  encryptedData:
    rabbitmq-password: AgAO3J7s74y9B9Ez1/FhHwRrJjsg2ACjMh42n/gIC7nkxe+3vA+Bw+aqRAkJWFu8+GnIu4ggdmjkNEPCgKusciSmN8VdwMBVcv7CBeqaHUadUe4v9aQ5iu4eFEX8WYKEXwwhIFIlM4yOfs0ffawGCcgaTMTuSfFIw5hMhLbs2tCLCuSZlIR0kQ822Mi2wQlWQoy9wY5HYxExDDcq08nMaUcj04dzLW7aEdPBEUJ+DXAD8qFIYF4s/x1HC/lFj2zCRRbDCQaDGuxzw7F9NZnZ5uD7EN2Ikmfz/WiwOX6mRE1bvTyvIDqTKC75//9DbHzVbnmR+mrCQsFU8OCBj+mYSTHL8HFZQUu89lWjnQj1wNxTBWawpzP9KXZ8P14sLsTnzPz3eZw59OZYHYQ9uc2hK1zZaHXqnF54hqRVDrnN7WyL8CYxotHl8XNV/tm8Y6Qy0/ro+J7IBBEXHITOVdLlbUdv2oMO5D2Ma6065sxXMW83h5mvFY116SVD7W8e00XWqM8yUOD+I+HM+V3hOYvkVApavrv/OcU2Mu5CMkH1u8Hq94y1NfHafftKxgXoMNPor3cWi5hZn0BvWjcjpwq46mK8MDXv3fWvJk2IIVKFqStBBuQ+3qtUycSUL9/ClfCqgMwDn9FKg9Arm2H/H338ctdEeWcGUaCFfna99RZyG2x628/Fr8cyUZPMAgTj21xS1h57Nvl4K9ZHUqRNYZy33G9qpMQP
  template:
    metadata:
      creationTimestamp: null
      name: comicrent-rabbitmq-secret
      namespace: sa-p8
    type: Opaque
