---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: comicrent-rabbitmq-secret
  namespace: sa-p9
spec:
  encryptedData:
    rabbitmq-password: AgAefq3oMTEpVDDbEmGOVmIRVDWn6VEkg/HHucDKc5nD7RU3B4HoYBi44VVe3DUPOlSkGTeCaW5bXRZqGDeEMY8NjqLO6gWALGZTHJoHRZx539uSV3TTSEFV8ybLODrWsrjUXMXRmUkapdSV5qHoBwlnPd2Jj3Zv3WdwLLuujxvzpdY0TYwucfcCHBQl3waYU1NX0LoR+Q9HEYxaNNldNfCH66VnwanUcbDPm+jpnGQ8wnEKpqWxksN7YcpC3yhYamqq2FW/s0HTrvINAGSuT1wRJ9+X4/mYUkDfIY8c3YrSFcfymWbnYlqvW/5Hi20FiVyZA3O18vLnUBv2YKeKqHDQixUVlZS3lVwDbC0BDa6PTHGc1bsDl4n1b1lTguY/d0gsRgdEcA96lA5l8NKsukicXUj6HbOyL1JTxpr7Ct6rXXbqGdlZKw8cAwD5UDm3oIbjzfxMxI0BRvS9WOsVy8AWQoFSbfdQQBnXdi1gzbW4cdlgyxjINJPI+kUDxSu2da8Xc+HlDsFLswqtEKG7PJu8711SsHXUKm2vELRChrlXM/lzPY6xYHWZrtU/j+xjuXGz8nLm5BS9xAI5wq0xtkFPxciX8oOPCtKU1ZRIc66caPyH4fln9bGSZEj39qsuJ5bBCM3N1BD/orqhH0Pfqj/mrTroPOgSnLf0PSvjm+Zblu9MP4rB4gb93YcjF/f2XCCSPiVBVmDPVOuQJ4CGRmTg04KrwmDfwATZbirLNkr1mA==
  template:
    metadata:
      creationTimestamp: null
      name: comicrent-rabbitmq-secret
      namespace: sa-p9
