---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: comicrent-postgresql-secret
  namespace: sa-p9
spec:
  encryptedData:
    password: AgCl5G/RoTxfQvLT2quVC6a49yMz8CB9QCFCtU/lKpVqbNcuEG+VDltZJ5manIYK5TXqGG3QWD5128ZFGnkooLjrdWRlEsSCs2jLIYt1uAkWcZDQkx0E3FhwPS6t3phe0dxKcWYFnR8jDbmIbAjlXzCIlkx1lqI8gWzE36lgJXFV7V1h1bXUKUA/23SfqMlZzq1b4wPZfBZH0SWqTbxO2LfHcAkl0Hmjek+HUepE9Fjs2W+rzgg1Jwq2MrDLyigMRk/VFV+S7U8cPDj9m6/CcU0AQI6s2okrROwcXqW/drT45IWM/7PGJxmCtbz0ffB7Th/D3PE2Xwjn4YESyYc7KBgDbFDuF+jLkqLdJLB89ZossQJ2kzlvgbE+1JUnO290OQ4Qba4r3Tjvl5TiJTtwUTEbzy8AF0X1b63h+TvMDabxd068+AafGc21kk0pl/AcXFiZvN1fJQkUCHWeUCl2/2q4LjyDqlaZUjp6+3icxbC7g0zmpzmTyBRwei7reBJTjqVzxBiSg2HOAde6tbdx7zJ5G933aX3fP2XP2FT3d1Q985+lQdNbZHP3Wo9dlIXl70l5byp+TyDkibLzJMxoPupvQD9UjU+f6M4WjpUw4XGJXEwuuxzmSkSeqtH5K9lsOX6dbuacQDeWvpZYGxyJfmwZugUNacEkgfZr+PhaxHysC3hfaMcGQQ2s6sIhQjglI/9qyrKtQnvNX0TU2d11sUifTrKc/rSwXA5NE7rpbK+i0Q==
    postgres-password: AgBrlZLbldOEivVFo0quGda554nDSYQrUnKhF3L9DpKpQBJhq+8BO9WVbMXtlx3eSlngQo9ewD1YxIQiXdLMdi9ZPSUjMiGNu91atirvxcHLwACn4HhOEEYa82P26FTkZ+kVuyWp7IX/+ufsjXffZJtFCQIL8DBN/ukvMM9KhnVWJBzBnBYxUWYsR0HV1dQzYxeIJ19LgMMgI8Eap3exjtBwi3WdjedbMM1zT6EwHMQEAM4+9P2b4lN2TB4CRrBAK+DBtOnSm7snpocDB9rUb01UDZ49kfwBjGPnKs8ZKu0alHtT5vEGVj0QTgiMIC7a+goRZj3qxDhVWWALJkxTuEnrLuklFI6e8NeOlYik3SV7AxkD6BlyWWMHFbTnLaangRocyuEccRmI9XqHwwhMn8WcR090WHgJ/4h71dwNJH87Iv11eXUsM298TtOm8LfJhq7ezpGYYM+alMs9Nk0vpiKBRJ4FJ3SH3NWmGCRye94dAtX5BrR0kEoGa9mK9BR+A+XM6EK7P5+qkKWO33/43Cu7MPaBSTRRx3plWH7cGVkko4KKAdlPHnjcEEBPvEdiJ71Rq7Q4m6z2FaKyN4cPvL7A58K2qy/2qL9AAhiO2WhivpYoXAMMP8GWcuWKs7xINwsgBmr6Aj1qHdrT39GIKkrjjVfLH00JvM66bb21Vn4KToCPj6M7USUMNzlzOIbhN0HiOA9djDkVZZGvxYy+UxZfyMhv51XAJEwG4PYtIBSYtA==
  template:
    metadata:
      creationTimestamp: null
      name: comicrent-postgresql-secret
      namespace: sa-p9
