{{- if .Values.global.secrets.create }}
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: comicrent-postgresql-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  postgres-password: {{ required "global.secrets.postgresPassword es obligatorio" .Values.global.secrets.postgresPassword | quote }}
  password: {{ required "global.secrets.postgresUserPassword es obligatorio" .Values.global.secrets.postgresUserPassword | quote }}

---
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: comicrent-rabbitmq-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  rabbitmq-password: {{ required "global.secrets.rabbitmqPassword es obligatorio" .Values.global.secrets.rabbitmqPassword | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: comicrent-auth-secret
  namespace: {{ .Values.namespace | default "sa-p5" | quote }}
  labels:
    app.kubernetes.io/part-of: "comicrent"
type: Opaque
stringData:
  JWT_SECRET: {{ required "global.secrets.jwtSecret es obligatorio" .Values.global.secrets.jwtSecret | quote }}
  ENCRYPTION_KEY: {{ required "global.secrets.encryptionKey es obligatorio" .Values.global.secrets.encryptionKey | quote }}
{{- end }}
