apiVersion: v1
kind: ServiceAccount
metadata:
  name: comicrent-cron-tick
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comicrent-cron-summary
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
automountServiceAccountToken: false

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: comicrent-summary-consumer
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
automountServiceAccountToken: false