apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "auth-service.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}

data:
  PORT: "3001"
  JWT_EXPIRES_IN: "60"
  JWT_REFRESH_TIME_SECONDS: "60"
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}