apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
automountServiceAccountToken: false