global:
  namespace: sa-p5

image:
  repository: comicrent/operations-jobs
  tag: "1.0.0"
  pullPolicy: IfNotPresent

database:
  host: comicrent-postgresql
  port: 5432
  username: comicrent_user
  name: operations_db
  existingSecret: ""
  urlKey: operations-database-url
  secretName: comicrent-postgresql-secret
  passwordKey: password

rabbitmq:
  host: comicrent-rabbitmq
  port: 5672
  username: comicrent
  exchange: comicrent.events
  routingKey: operations.hourly.summary
  queue: operations.hourly.summary
  secretName: comicrent-rabbitmq-secret
  passwordKey: rabbitmq-password

cronTick:
  schedule: "*/2 * * * *"

cronSummary:
  schedule: "*/10 * * * *"

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 150m
    memory: 128Mi

summaryConsumer:
  probes:
    startup:
      failureThreshold: 30
      periodSeconds: 2
      timeoutSeconds: 3

    readiness:
      initialDelaySeconds: 5
      periodSeconds: 10
      failureThreshold: 3
      timeoutSeconds: 3

    liveness:
      initialDelaySeconds: 15
      periodSeconds: 15
      failureThreshold: 3
      timeoutSeconds: 3
