apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api-gateway.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  PORT: "3000"
  AUTH_SERVICE_URL: "http://comicrent-auth-service:3001"
  COMICS_SERVICE_URL: "http://comicrent-comics-service:3002/graphql"
  RENTALS_SERVICE_URL: "http://comicrent-rentals-service:8001/graphql"
  COPIES_SERVICE_URL: "http://comicrent-copies-service:8002"
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}