apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api-gateway.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
automountServiceAccountToken: false