global:
  secrets:
    postgresPassword: "CHANGE_ME"
    postgresUserPassword: "CHANGE_ME"
    rabbitmqPassword: "CHANGE_ME"
    jwtSecret: "CHANGE_ME"
    encryptionKey: "CHANGE_ME_64_HEX_CHARACTERS"