# Ejemplo de gestión segura. Los valores reales se generan con kubeseal y nunca se guardan en texto plano.
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: comicrent-database-secret
  namespace: sa-p8
spec:
  encryptedData: {}
  template:
    metadata:
      name: comicrent-database-secret
      namespace: sa-p8
    type: Opaque
