apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comicrent-p8-policies
  namespace: argocd
spec:
  project: comicrent-p8
  source:
    repoURL: https://github.com/DavidVelasquez77/Practicas-SA-B-202307705-gitops.git
    targetRevision: main
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
