apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: comicrent-p8
  namespace: argocd
spec:
  description: ComicRent P8 GitOps project
  sourceRepos:
    - https://github.com/DavidVelasquez77/Practicas-SA-B-202307705-gitops.git
  destinations:
    - namespace: sa-p8
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:`n    - group: ""`n      kind: Namespace`n    - group: argoproj.io`n      kind: Rollout`n    - group: argoproj.io`n      kind: AnalysisTemplate`n    - group: kyverno.io`n      kind: ClusterPolicy`n  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

