apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "copies-consumer.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "copies-consumer.labels" . | nindent 4 }}
automountServiceAccountToken: false