apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rentals-service.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "rentals-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | default "8001" | quote }}

  HTTP_TIMEOUT_SECONDS: "5"

  COMICS_SERVICE_URL: "http://comicrent-comics-service:3002/graphql"

  COPIES_SERVICE_URL: "http://comicrent-copies-service:8002"

  RABBITMQ_HOST: "comicrent-rabbitmq"

  RABBITMQ_PORT: "5672"

  RABBITMQ_USER: "comicrent"

  RABBITMQ_EXCHANGE: "comicrent.events"

  RABBITMQ_RETURN_ROUTING_KEY: "copy.return.requested"

  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}