apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rentals-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "rentals-service.labels" . | nindent 4 }}

subjects:
  - kind: ServiceAccount
    name: {{ include "rentals-service.fullname" . }}
    namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rentals-service.fullname" . }}