apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "comics-service.fullname" . }}-config
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "comics-service.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | default "3002" | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | default "info" | quote }}