apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "comics-service.fullname" . }}
  namespace: {{ .Values.global.namespace | default "sa-p5" | quote }}
  labels:
    {{- include "comics-service.labels" . | nindent 4 }}
rules: []