apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comicrent-p8-workloads
  namespace: argocd
  annotations: { argocd.argoproj.io/sync-wave: "7" }
spec:
  project: comicrent-p9
  source:
    repoURL: https://github.com/DavidVelasquez77/Practicas-SA-B-202307705-gitops.git
    targetRevision: p9-continuidad-operativa
    path: apps/comicrent
    helm:
      valueFiles: [values-gke.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p8
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=false, ServerSideApply=true]
