apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: comicrent-p9-workloads
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: comicrent-p9
spec:
  project: comicrent-p9
  source:
    repoURL: https://github.com/DavidVelasquez77/Practicas-SA-B-202307705-gitops.git
    targetRevision: p9-continuidad-operativa
    path: apps/comicrent
    helm:
      valueFiles:
        - values-p9.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sa-p9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
